### ISSUE TITLE
Better output

### ISSUE THREAD

**Issue by ganlanyuan** [gchudnov/gulp-w3c-css#2]
Is it possible to set output file to `.json` instead of `.css`?
Or even better to have html reports?

**Comment by gchudnov** [comment]
I think you can change the extension of the resulting file(s) if you change
```
.pipe(gulp.dest(dstPath))
```
to something like this:
```
.pipe(dest(dstPath, {ext: '.json'}))
```

Or even better to have html reports?
^^
It looks I don't have enough time to implement that. Pull requests are always welcome!

**Comment by ganlanyuan** [comment]
`.pipe(dest(dstPath, {ext: '.json'}))` doesn't work, but I achieve this with [gulp-rename](https://github.com/hparra/gulp-rename):
```
return gulp.src(src)
  .pipe($.w3cCss())
  .pipe($.rename({extname: '.json'}))
  .pipe(gulp.dest('w3cErrors/css'));
```

Thanks anyway!
